stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest
  - mavendeploy

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn package

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/ISU_Swap/gradlew
  tags:
   - androidstudio
   - frontend
  script:
    - cd Frontend/ISU_Swap
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/ISU_Swap/gradlew
  tags:
   - androidstudio
   - frontend
  script:
    - cd Frontend/ISU_Swap
    - ./gradlew test

autoDeploy:
  stage: mavendeploy
  tags:
   - springboot_tag
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
